#!/bin/sh
#
# AutoTweaker
# Copyright (C) 2026  WhiteElephant-abc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl --global disable --now autotweaker 2>/dev/null || true
    pkill -f "io.github.autotweaker.core.MainKt" 2>/dev/null || true
    rm -f /usr/bin/autotweaker
    rm -f /usr/lib/systemd/user/autotweaker.service
    rm -rf /usr/libexec/autotweaker
    systemctl --global daemon-reload 2>/dev/null || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /etc/autotweaker
fi
