#!/bin/sh
#
# AutoTweaker
# Copyright (C) 2026  WhiteElephant-abc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ] || [ "$1" = "upgrade" ]; then
    systemctl --global disable --now autotweaker 2>/dev/null || true
    for user in $(loginctl list-users --no-legend 2>/dev/null | awk '{print $2}'); do
        su -s /bin/sh -c "XDG_RUNTIME_DIR=/run/user/\$(id -u) systemctl --user disable --now autotweaker" "$user" || true
    done
    systemctl stop autotweaker-update.timer 2>/dev/null || true
    systemctl stop autotweaker-update.service 2>/dev/null || true
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl disable autotweaker-update.timer 2>/dev/null || true
    systemctl disable autotweaker-update.service 2>/dev/null || true
fi
