name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          validate-wrappers: false

      - name: Build
        run: >
          ./gradlew build
          -Dhttp.proxyHost= -Dhttp.proxyPort=
          -Dhttps.proxyHost= -Dhttps.proxyPort=
          -Dorg.gradle.java.installations.auto-download=true
